package su.kamil.dev.golos.app.ui

import java.util.concurrent.CopyOnWriteArrayList

enum class AppLanguage(val code: String, val displayName: String) {
    EN("en", "English"),
    FR("fr", "Français (French)"),
    DE("de", "Deutsch (German)"),
    RU("ru", "Русский (Russian)"),
    JP("ja", "日本語 (Japanese)"),
    CN("zh", "中文 (Chinese)"),
    TR("tr", "Türkçe (Turkish)"),
    AR("ar", "العربية (Arabic)"),
    ES("es", "Español (Spanish)"),
    IT("it", "Italiano (Italian)"),
    ;

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: EN
        }
    }
}

object AppLocalization {
    var currentLanguage: AppLanguage = AppLanguage.EN
        private set

    private val listeners = CopyOnWriteArrayList<() -> Unit>()

    fun setLanguage(lang: AppLanguage) {
        if (currentLanguage != lang) {
            currentLanguage = lang
            listeners.forEach { it.invoke() }
        }
    }

    fun addLanguageChangeListener(listener: () -> Unit) {
        listeners.add(listener)
    }

    private val translations =
        mapOf(
            AppLanguage.EN to
                mapOf(
                    "tab.dashboard" to "Dashboard",
                    "tab.settings" to "Settings",
                    "tab.whisper" to "Whisper & Models",
                    "tab.history" to "History",
                    "tab.batch" to "Batch Audio",
                    "bulb.app.title" to "APP",
                    "bulb.app.active" to "ACTIVE",
                    "bulb.voice.title" to "VOICE",
                    "bulb.voice.idle" to "IDLE",
                    "bulb.voice.listening" to "LISTENING",
                    "bulb.voice.processing" to "PROCESSING",
                    "bulb.voice.transcribing" to "TRANSCRIBING",
                    "bulb.mode.title" to "MODE",
                    "btn.hold_to_speak" to "Hold to Speak (Push to Talk)",
                    "btn.recording" to "Recording... Release to transcribe",
                    "btn.processing" to "Processing speech...",
                    "btn.copy" to "Copy",
                    "btn.collapse" to "Collapse to Bulbs",
                    "btn.expand" to "Expand Window",
                    "btn.hide_tray" to "Hide to Tray",
                    "btn.exit" to "Exit Application",
                    "btn.open_settings" to "Open Settings...",
                    "btn.record_shortcut" to "Record Shortcut (Click & Press Keys)",
                    "btn.apply" to "Apply",
                    "btn.reset_defaults" to "Reset to Defaults",
                    "btn.export" to "Export Settings...",
                    "btn.import" to "Import Settings...",
                    "btn.download_binary" to "Download whisper-cli",
                    "btn.browse" to "Browse...",
                    "btn.download_model" to "Download Model",
                    "btn.transcribe_file" to "Transcribe Audio File...",
                    "btn.clear_history" to "Clear History",
                    "label.audio_provider" to "Audio Provider:",
                    "label.microphone" to "Audio Input / Monitor:",
                    "label.engine" to "Recognition Engine:",
                    "label.hotkey" to "Push-to-Talk Hotkey:",
                    "label.insertion_mode" to "Text Insertion Mode:",
                    "label.timing" to "Insertion Timing:",
                    "label.clipboard_privacy" to "Clipboard Privacy:",
                    "label.system_startup" to "System Startup:",
                    "label.whisper_exec" to "Whisper Executable:",
                    "label.multilingual_model" to "Multilingual Model:",
                    "label.spoken_lang" to "Spoken Language:",
                    "label.bilingual_mode" to "Bilingual Mode:",
                    "label.inference_device" to "Inference Device:",
                    "label.ui_language" to "Interface Language:",
                    "label.recent_speech" to "Recent Speech Transcription:",
                    "label.search_history" to "Search History:",
                    "label.hotkey_plus_key" to "+ Key:",
                    "label.history_total" to "Total: %d entries",
                    "mode.release" to "On Key Release",
                    "mode.fly" to "On the Fly",
                    "mode.direct" to "Direct Typing",
                    "mode.clipboard" to "Clipboard",
                    "placeholder.no_dictations" to "No dictations yet. Hold your hotkey or press Hold to Speak.",
                    "opt.audio.javasound" to "JavaSound (Standard Cross-Platform)",
                    "opt.audio.portaudio" to "PortAudio (Alternative Native)",
                    "opt.ins.direct" to "Direct Typing (Privacy-preserving)",
                    "opt.ins.clipboard" to "Clipboard Paste (Ctrl+V)",
                    "opt.timing.release" to "On Key Release (Default - Whole phrase)",
                    "opt.timing.onthefly" to "On the Fly (Incremental live typing)",
                    "opt.device.cpu" to "CPU (Standard)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan)",
                    "lang.auto" to "Auto-Detect (auto)",
                    "lang.en" to "English (en)",
                    "lang.fr" to "French (fr)",
                    "lang.de" to "German (de)",
                    "lang.ru" to "Russian (ru)",
                    "lang.ja" to "Japanese (ja)",
                    "lang.zh" to "Chinese (zh)",
                    "lang.tr" to "Turkish (tr)",
                    "lang.ar" to "Arabic (ar)",
                    "lang.es" to "Spanish (es)",
                    "lang.it" to "Italian (it)",
                    "lang.pt" to "Portuguese (pt)",
                    "lang.ko" to "Korean (ko)",
                    "lang.uk" to "Ukrainian (uk)",
                    "lang.pl" to "Polish (pl)",
                    "lang.nl" to "Dutch (nl)",
                    "check.bilingual" to "Bilingual Mode (EN + Selected Language)",
                    "check.copy_clipboard" to "Save transcription to clipboard",
                    "check.fallback_clipboard" to "Save to clipboard if no active field focused",
                    "check.autostart" to "Start GolosAI automatically on system login",
                    "status.checking_binary" to "Checking whisper-cli...",
                    "status.model_checking" to "Status: Checking...",
                    "status.model_downloaded" to "Status: Downloaded",
                    "status.model_not_found" to "Status: Not found",
                    "label.model_status" to "Model Status:",
                    "label.download_progress" to "Download Progress:",
                    "label.audio_file_dictation" to "Audio File Dictation:",
                    "btn.redownload" to "Re-download",
                    "btn.download" to "Download",
                    "tip.bilingual" to "Allows mixed code-switching between English and selected language",
                    "tip.download_cli" to "Download precompiled whisper-cli binary",
                    "tip.key_field" to "Key (e.g. L, F8, Space, Return)",
                    "tip.reset_defaults" to "Reset all settings to initial defaults",
                    "tip.export" to "Export settings to YAML file",
                    "tip.import" to "Import settings from YAML file",
                    "metric.current_title" to "CURRENT TEXT",
                    "metric.history_mean_title" to "HISTORY MEAN",
                    "metric.all_time_title" to "ALL TIME",
                    "opt.trigger.hold" to "Hold to Talk (Continuous press)",
                    "opt.trigger.toggle" to "Toggle On/Off (Press to start/stop)",
                    "label.trigger_mode" to "Hotkey Trigger Mode:",
                    "label.input_gain" to "Microphone Gain:",
                    "label.input_level" to "Audio Input Level:",
                    "btn.test_mic" to "Test Mic",
                    "btn.stop_test" to "Stop Test",
                    "warning.silence" to "Microphone muted or volume too low",
                    "warning.clipping" to "Audio clipping detected; lower input volume",
                ),
            AppLanguage.FR to
                mapOf(
                    "tab.dashboard" to "Tableau de bord",
                    "tab.settings" to "Paramètres",
                    "tab.whisper" to "Whisper et Modèles",
                    "tab.history" to "Historique",
                    "tab.batch" to "Traitement par lots",
                    "bulb.app.title" to "APPLI",
                    "bulb.app.active" to "ACTIF",
                    "bulb.voice.title" to "VOIX",
                    "bulb.voice.idle" to "EN ATTENTE",
                    "bulb.voice.listening" to "ÉCOUTE",
                    "bulb.voice.processing" to "TRAITEMENT",
                    "bulb.voice.transcribing" to "TRANSCRIPTION",
                    "bulb.mode.title" to "MODE",
                    "btn.hold_to_speak" to "Maintenir pour parler",
                    "btn.recording" to "Enregistrement... Relâchez",
                    "btn.processing" to "Traitement de la voix...",
                    "btn.copy" to "Copier",
                    "btn.collapse" to "Réduire aux voyants",
                    "btn.expand" to "Agrandir",
                    "btn.hide_tray" to "Réduire dans la barre",
                    "btn.exit" to "Quitter l'application",
                    "btn.open_settings" to "Paramètres...",
                    "btn.record_shortcut" to "Enregistrer un raccourci",
                    "btn.apply" to "Appliquer",
                    "btn.reset_defaults" to "Réinitialiser",
                    "btn.export" to "Exporter les paramètres...",
                    "btn.import" to "Importer les paramètres...",
                    "btn.download_binary" to "Télécharger whisper-cli",
                    "btn.browse" to "Parcourir...",
                    "btn.download_model" to "Télécharger le modèle",
                    "btn.transcribe_file" to "Transcrire un fichier audio...",
                    "btn.clear_history" to "Effacer l'historique",
                    "label.audio_provider" to "Fournisseur audio:",
                    "label.microphone" to "Entrée audio / Moniteur:",
                    "label.engine" to "Moteur de reconnaissance:",
                    "label.hotkey" to "Raccourci push-to-talk:",
                    "label.insertion_mode" to "Mode d'insertion de texte:",
                    "label.timing" to "Moment d'insertion:",
                    "label.clipboard_privacy" to "Confidentialité presse-papiers:",
                    "label.system_startup" to "Démarrage système:",
                    "label.whisper_exec" to "Exécutable Whisper:",
                    "label.multilingual_model" to "Modèle multilingue:",
                    "label.spoken_lang" to "Langue parlée:",
                    "label.bilingual_mode" to "Mode bilingue:",
                    "label.inference_device" to "Périphérique de calcul:",
                    "label.ui_language" to "Langue de l'interface:",
                    "label.recent_speech" to "Transcription vocale récente:",
                    "label.search_history" to "Rechercher dans l'historique:",
                    "label.hotkey_plus_key" to "+ Touche :",
                    "label.history_total" to "Total : %d entrées",
                    "mode.release" to "Au relâchement",
                    "mode.fly" to "À la volée",
                    "mode.direct" to "Saisie directe",
                    "mode.clipboard" to "Presse-papiers",
                    "placeholder.no_dictations" to "Aucune dictée pour le moment. Maintenez le raccourci ou appuyez sur Parler.",
                    "opt.audio.javasound" to "JavaSound (Standard multiplateforme)",
                    "opt.audio.portaudio" to "PortAudio (Natif alternatif)",
                    "opt.ins.direct" to "Saisie directe (Confidentialité)",
                    "opt.ins.clipboard" to "Presse-papiers (Ctrl+V)",
                    "opt.timing.release" to "Au relâchement (Par défaut - Phrase entière)",
                    "opt.timing.onthefly" to "À la volée (Frappe incrémentielle)",
                    "opt.device.cpu" to "CPU (Standard)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan)",
                    "lang.auto" to "Détection automatique (auto)",
                    "lang.en" to "Anglais (en)",
                    "lang.fr" to "Français (fr)",
                    "lang.de" to "Allemand (de)",
                    "lang.ru" to "Russe (ru)",
                    "lang.ja" to "Japonais (ja)",
                    "lang.zh" to "Chinois (zh)",
                    "lang.tr" to "Turc (tr)",
                    "lang.ar" to "Arabe (ar)",
                    "lang.es" to "Espagnol (es)",
                    "lang.it" to "Italien (it)",
                    "lang.pt" to "Portugais (pt)",
                    "lang.ko" to "Coréen (ko)",
                    "lang.uk" to "Ukrainien (uk)",
                    "lang.pl" to "Polonais (pl)",
                    "lang.nl" to "Néerlandais (nl)",
                    "check.bilingual" to "Mode bilingue (EN + Langue sélectionnée)",
                    "check.copy_clipboard" to "Enregistrer la transcription dans le presse-papiers",
                    "check.fallback_clipboard" to "Dans le presse-papiers si aucun champ actif",
                    "check.autostart" to "Lancer GolosAI au démarrage du système",
                    "status.checking_binary" to "Vérification de whisper-cli...",
                    "status.model_checking" to "État : Vérification...",
                    "status.model_downloaded" to "État : Téléchargé",
                    "status.model_not_found" to "État : Non trouvé",
                    "label.model_status" to "État du modèle :",
                    "label.download_progress" to "Progression du téléchargement :",
                    "label.audio_file_dictation" to "Dictée de fichier audio :",
                    "btn.redownload" to "Retélécharger",
                    "btn.download" to "Télécharger",
                    "tip.bilingual" to "Permet l'alternance codique entre anglais et langue choisie",
                    "tip.download_cli" to "Télécharger l'exécutable whisper-cli précompilé",
                    "tip.key_field" to "Touche (ex. L, F8, Espace, Entrée)",
                    "tip.reset_defaults" to "Restaurer les paramètres par défaut",
                    "tip.export" to "Exporter les paramètres en YAML",
                    "tip.import" to "Importer les paramètres depuis YAML",
                    "metric.current_title" to "TEXTE ACTUEL",
                    "metric.history_mean_title" to "MOYENNE HISTORIQUE",
                    "metric.all_time_title" to "TOUT TEMPS",
                    "opt.trigger.hold" to "Maintenir pour parler",
                    "opt.trigger.toggle" to "Bascule Marche/Arrêt",
                    "label.trigger_mode" to "Mode de déclenchement :",
                    "label.input_gain" to "Gain du microphone :",
                    "label.input_level" to "Niveau d'entrée audio :",
                    "btn.test_mic" to "Tester micro",
                    "btn.stop_test" to "Arrêter test",
                    "warning.silence" to "Microphone coupé ou volume trop bas",
                    "warning.clipping" to "Écrêtage audio détecté ; baissez le volume",
                ),
            AppLanguage.DE to
                mapOf(
                    "tab.dashboard" to "Übersicht",
                    "tab.settings" to "Einstellungen",
                    "tab.whisper" to "Whisper & Modelle",
                    "tab.history" to "Verlauf",
                    "tab.batch" to "Stapelverarbeitung",
                    "bulb.app.title" to "APP",
                    "bulb.app.active" to "AKTIV",
                    "bulb.voice.title" to "STIMME",
                    "bulb.voice.idle" to "BEREIT",
                    "bulb.voice.listening" to "HÖRT ZU",
                    "bulb.voice.processing" to "VERARBEITUNG",
                    "bulb.voice.transcribing" to "TRANSKRIPTION",
                    "bulb.mode.title" to "MODUS",
                    "btn.hold_to_speak" to "Halten zum Sprechen",
                    "btn.recording" to "Aufnahme... Loslassen",
                    "btn.processing" to "Sprachverarbeitung...",
                    "btn.copy" to "Kopieren",
                    "btn.collapse" to "Auf Leuchten minimieren",
                    "btn.expand" to "Fenster vergrößern",
                    "btn.hide_tray" to "In Infobereich minimieren",
                    "btn.exit" to "Beenden",
                    "btn.open_settings" to "Einstellungen...",
                    "btn.record_shortcut" to "Tastenkombination aufnehmen",
                    "btn.apply" to "Anwenden",
                    "btn.reset_defaults" to "Auf Standard zurücksetzen",
                    "btn.export" to "Einstellungen exportieren...",
                    "btn.import" to "Einstellungen importieren...",
                    "btn.download_binary" to "whisper-cli herunterladen",
                    "btn.browse" to "Durchsuchen...",
                    "btn.download_model" to "Modell herunterladen",
                    "btn.transcribe_file" to "Audiodatei transkribieren...",
                    "btn.clear_history" to "Verlauf löschen",
                    "label.audio_provider" to "Audio-Anbieter:",
                    "label.microphone" to "Audioeingang / Monitor:",
                    "label.engine" to "Erkennungs-Engine:",
                    "label.hotkey" to "Push-to-Talk Hotkey:",
                    "label.insertion_mode" to "Texteinfügemodus:",
                    "label.timing" to "Einfügezeitpunkt:",
                    "label.clipboard_privacy" to "Zwischenablage-Datenschutz:",
                    "label.system_startup" to "Systemstart:",
                    "label.whisper_exec" to "Whisper-Programm:",
                    "label.multilingual_model" to "Mehrsprachiges Modell:",
                    "label.spoken_lang" to "Gesprochene Sprache:",
                    "label.bilingual_mode" to "Bilingualer Modus:",
                    "label.inference_device" to "Inferenzgerät:",
                    "label.ui_language" to "Oberflächensprache:",
                    "label.recent_speech" to "Letzte Sprachtranskription:",
                    "label.search_history" to "Verlauf durchsuchen:",
                    "label.hotkey_plus_key" to "+ Taste:",
                    "label.history_total" to "Gesamt: %d Einträge",
                    "mode.release" to "Beim Loslassen",
                    "mode.fly" to "In Echtzeit",
                    "mode.direct" to "Direkte Eingabe",
                    "mode.clipboard" to "Zwischenablage",
                    "placeholder.no_dictations" to "Noch keine Diktate. Halten Sie Ihren Hotkey oder drücken Sie Sprechen.",
                    "opt.audio.javasound" to "JavaSound (Plattformübergreifender Standard)",
                    "opt.audio.portaudio" to "PortAudio (Alternative nativer Treiber)",
                    "opt.ins.direct" to "Direktes Tippen (Datenschutz)",
                    "opt.ins.clipboard" to "Zwischenablage einfügen (Strg+V)",
                    "opt.timing.release" to "Beim Loslassen (Standard - Ganzer Satz)",
                    "opt.timing.onthefly" to "In Echtzeit (Fortlaufende Eingabe)",
                    "opt.device.cpu" to "CPU (Standard)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan)",
                    "lang.auto" to "Automatische Erkennung (auto)",
                    "lang.en" to "Englisch (en)",
                    "lang.fr" to "Französisch (fr)",
                    "lang.de" to "Deutsch (de)",
                    "lang.ru" to "Russisch (ru)",
                    "lang.ja" to "Japanisch (ja)",
                    "lang.zh" to "Chinesisch (zh)",
                    "lang.tr" to "Türkisch (tr)",
                    "lang.ar" to "Arabisch (ar)",
                    "lang.es" to "Spanisch (es)",
                    "lang.it" to "Italienisch (it)",
                    "lang.pt" to "Portugiesisch (pt)",
                    "lang.ko" to "Koreanisch (ko)",
                    "lang.uk" to "Ukrainisch (uk)",
                    "lang.pl" to "Polnisch (pl)",
                    "lang.nl" to "Niederländisch (nl)",
                    "check.bilingual" to "Bilingualer Modus (EN + Ausgewählte Sprache)",
                    "check.copy_clipboard" to "Transkription in Zwischenablage speichern",
                    "check.fallback_clipboard" to "In Zwischenablage wenn kein aktives Textfeld",
                    "check.autostart" to "GolosAI beim Systemstart automatisch starten",
                    "status.checking_binary" to "Prüfe whisper-cli...",
                    "status.model_checking" to "Status: Prüfen...",
                    "status.model_downloaded" to "Status: Heruntergeladen",
                    "status.model_not_found" to "Status: Nicht gefunden",
                    "label.model_status" to "Modellstatus:",
                    "label.download_progress" to "Download-Fortschritt:",
                    "label.audio_file_dictation" to "Audiodatei-Diktat:",
                    "btn.redownload" to "Erneut herunterladen",
                    "btn.download" to "Herunterladen",
                    "tip.bilingual" to "Ermöglicht Sprachwechsel zwischen Englisch und gewählter Sprache",
                    "tip.download_cli" to "Vorkompilierte whisper-cli herunterladen",
                    "tip.key_field" to "Taste (z. B. L, F8, Leertaste, Eingabe)",
                    "tip.reset_defaults" to "Alle Einstellungen auf Standard zurücksetzen",
                    "tip.export" to "Einstellungen in YAML-Datei exportieren",
                    "tip.import" to "Einstellungen aus YAML-Datei importieren",
                    "metric.current_title" to "AKTUELLER TEXT",
                    "metric.history_mean_title" to "VERLAUFS-DURCHSCHNITT",
                    "metric.all_time_title" to "GESAMTZEIT",
                    "opt.trigger.hold" to "Gedrückt halten zum Sprechen",
                    "opt.trigger.toggle" to "Umschalten Ein/Aus",
                    "label.trigger_mode" to "Auslösemodus:",
                    "label.input_gain" to "Mikrofonverstärkung:",
                    "label.input_level" to "Audioeingangspegel:",
                    "btn.test_mic" to "Mikrofon testen",
                    "btn.stop_test" to "Test beenden",
                    "warning.silence" to "Mikrofon stummgeschaltet oder Pegel zu niedrig",
                    "warning.clipping" to "Audioübersteuerung erkannt; Eingangspegel senken",
                ),
            AppLanguage.RU to
                mapOf(
                    "tab.dashboard" to "Панель управления",
                    "tab.settings" to "Настройки",
                    "tab.whisper" to "Whisper и Модели",
                    "tab.history" to "История",
                    "tab.batch" to "Пакетное распознавание",
                    "bulb.app.title" to "ПРИЛ",
                    "bulb.app.active" to "АКТИВНО",
                    "bulb.voice.title" to "ГОЛОС",
                    "bulb.voice.idle" to "ОЖИДАНИЕ",
                    "bulb.voice.listening" to "СЛУШАЕТ",
                    "bulb.voice.processing" to "ОБРАБОТКА",
                    "bulb.voice.transcribing" to "РАСПОЗНАВАНИЕ",
                    "bulb.mode.title" to "РЕЖИМ",
                    "btn.hold_to_speak" to "Удерживайте чтобы говорить",
                    "btn.recording" to "Запись... Отпустите для ввода",
                    "btn.processing" to "Обработка речи...",
                    "btn.copy" to "Копировать",
                    "btn.collapse" to "Свернуть в индикаторы",
                    "btn.expand" to "Развернуть окно",
                    "btn.hide_tray" to "Свернуть в трей",
                    "btn.exit" to "Выход из программы",
                    "btn.open_settings" to "Открыть настройки...",
                    "btn.record_shortcut" to "Записать сочетание",
                    "btn.apply" to "Применить",
                    "btn.reset_defaults" to "Сбросить по умолчанию",
                    "btn.export" to "Экспорт настроек...",
                    "btn.import" to "Импорт настроек...",
                    "btn.download_binary" to "Скачать whisper-cli",
                    "btn.browse" to "Обзор...",
                    "btn.download_model" to "Скачать модель",
                    "btn.transcribe_file" to "Распознать аудиофайл...",
                    "btn.clear_history" to "Очистить историю",
                    "label.audio_provider" to "Аудио-драйвер:",
                    "label.microphone" to "Входной микрофон / Монитор:",
                    "label.engine" to "Движок распознавания:",
                    "label.hotkey" to "Горячая клавиша PTT:",
                    "label.insertion_mode" to "Способ вставки текста:",
                    "label.timing" to "Момент вставки текста:",
                    "label.clipboard_privacy" to "Приватность буфера:",
                    "label.system_startup" to "Автозапуск:",
                    "label.whisper_exec" to "Исполняемый файл Whisper:",
                    "label.multilingual_model" to "Мультиязычная модель:",
                    "label.spoken_lang" to "Язык диктовки:",
                    "label.bilingual_mode" to "Билингвальный режим:",
                    "label.inference_device" to "Устройство инференса:",
                    "label.ui_language" to "Язык интерфейса:",
                    "label.recent_speech" to "Недавняя расшифровка:",
                    "label.search_history" to "Поиск по истории:",
                    "label.hotkey_plus_key" to "+ Клавиша:",
                    "label.history_total" to "Всего: %d записей",
                    "mode.release" to "По отпусканию клавиши",
                    "mode.fly" to "На лету",
                    "mode.direct" to "Прямой ввод",
                    "mode.clipboard" to "Буфер обмена",
                    "placeholder.no_dictations" to "Диктовки отсутствуют. Удерживайте горячую клавишу или нажмите «Говорить».",
                    "opt.audio.javasound" to "JavaSound (Стандартный кроссплатформенный)",
                    "opt.audio.portaudio" to "PortAudio (Альтернативный нативный)",
                    "opt.ins.direct" to "Прямой ввод (Конфиденциальный)",
                    "opt.ins.clipboard" to "Вставка через буфер (Ctrl+V)",
                    "opt.timing.release" to "При отпускании клавиши (По умолчанию)",
                    "opt.timing.onthefly" to "На лету (Инкрементальный ввод)",
                    "opt.device.cpu" to "CPU (Стандартный)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan)",
                    "lang.auto" to "Автоопределение (auto)",
                    "lang.en" to "Английский (en)",
                    "lang.fr" to "Французский (fr)",
                    "lang.de" to "Немецкий (de)",
                    "lang.ru" to "Русский (ru)",
                    "lang.ja" to "Японский (ja)",
                    "lang.zh" to "Китайский (zh)",
                    "lang.tr" to "Турецкий (tr)",
                    "lang.ar" to "Арабский (ar)",
                    "lang.es" to "Испанский (es)",
                    "lang.it" to "Итальянский (it)",
                    "lang.pt" to "Португальский (pt)",
                    "lang.ko" to "Корейский (ko)",
                    "lang.uk" to "Украинский (uk)",
                    "lang.pl" to "Польский (pl)",
                    "lang.nl" to "Нидерландский (nl)",
                    "check.bilingual" to "Двуязычный режим (EN + выбранный язык)",
                    "check.copy_clipboard" to "Сохранять транскрипцию в буфер обмена",
                    "check.fallback_clipboard" to "В буфер, если нет активного поля ввода",
                    "check.autostart" to "Запускать GolosAI при входе в систему",
                    "status.checking_binary" to "Проверка whisper-cli...",
                    "status.model_checking" to "Статус: Проверка...",
                    "status.model_downloaded" to "Статус: Загружена",
                    "status.model_not_found" to "Статус: Не найдена",
                    "label.model_status" to "Статус модели:",
                    "label.download_progress" to "Прогресс загрузки:",
                    "label.audio_file_dictation" to "Диктовка аудиофайла:",
                    "btn.redownload" to "Перезагрузить",
                    "btn.download" to "Скачать",
                    "tip.bilingual" to "Позволяет смешанное распознавание английского и выбранного языка",
                    "tip.download_cli" to "Скачать скомпилированный бинарник whisper-cli",
                    "tip.key_field" to "Клавиша (напр. L, F8, Space, Return)",
                    "tip.reset_defaults" to "Сбросить все настройки к начальным",
                    "tip.export" to "Экспортировать настройки в YAML",
                    "tip.import" to "Импортировать настройки из YAML",
                    "metric.current_title" to "ТЕКУЩИЙ ТЕКСТ",
                    "metric.history_mean_title" to "СРЕДНЕЕ ПО ИСТОРИИ",
                    "metric.all_time_title" to "ЗА ВСЁ ВРЕМЯ",
                    "opt.trigger.hold" to "Удержание клавиши (Push-to-Talk)",
                    "opt.trigger.toggle" to "Переключатель вкл/выкл (Toggle)",
                    "label.trigger_mode" to "Режим активации:",
                    "label.input_gain" to "Усиление микрофона:",
                    "label.input_level" to "Уровень входного сигнала:",
                    "btn.test_mic" to "Проверить микрофон",
                    "btn.stop_test" to "Остановить проверку",
                    "warning.silence" to "Микрофон отключен или сигнал слишком тихий",
                    "warning.clipping" to "Обнаружен клиппинг звука; снизьте громкость",
                ),
            AppLanguage.JP to
                mapOf(
                    "tab.dashboard" to "ダッシュボード",
                    "tab.settings" to "設定",
                    "tab.whisper" to "Whisperとモデル",
                    "tab.history" to "履歴",
                    "tab.batch" to "一括処理",
                    "bulb.app.title" to "アプリ",
                    "bulb.app.active" to "稼働中",
                    "bulb.voice.title" to "音声",
                    "bulb.voice.idle" to "待機中",
                    "bulb.voice.listening" to "聞き取り中",
                    "bulb.voice.processing" to "処理中",
                    "bulb.voice.transcribing" to "変換中",
                    "bulb.mode.title" to "モード",
                    "btn.hold_to_speak" to "長押しで話す (PTT)",
                    "btn.recording" to "録音中... 離して確定",
                    "btn.processing" to "音声を変換中...",
                    "btn.copy" to "コピー",
                    "btn.collapse" to "ランプに折りたたむ",
                    "btn.expand" to "ウィンドウを展開",
                    "btn.hide_tray" to "トレイに格納",
                    "btn.exit" to "終了",
                    "btn.open_settings" to "設定を開く...",
                    "btn.record_shortcut" to "ショートカットを録音/登録",
                    "btn.apply" to "適用",
                    "btn.reset_defaults" to "初期設定に戻す",
                    "btn.export" to "設定を書き出し...",
                    "btn.import" to "設定を読み込み...",
                    "btn.download_binary" to "whisper-cli をダウンロード",
                    "btn.browse" to "参照...",
                    "btn.download_model" to "モデルをダウンロード",
                    "btn.transcribe_file" to "音声ファイルを変換...",
                    "btn.clear_history" to "履歴を消去",
                    "label.audio_provider" to "オーディオドライバ:",
                    "label.microphone" to "マイク / モニター:",
                    "label.engine" to "認識エンジン:",
                    "label.hotkey" to "ホットキー:",
                    "label.insertion_mode" to "文字入力方式:",
                    "label.timing" to "入力確定タイミング:",
                    "label.clipboard_privacy" to "クリップボード保護:",
                    "label.system_startup" to "自動起動設定:",
                    "label.whisper_exec" to "Whisper 実行ファイル:",
                    "label.multilingual_model" to "多言語モデル:",
                    "label.spoken_lang" to "音声の言語:",
                    "label.bilingual_mode" to "バイリンガルモード:",
                    "label.inference_device" to "計算デバイス:",
                    "label.ui_language" to "UI表示言語:",
                    "label.recent_speech" to "直近の音声文字起こし:",
                    "label.search_history" to "履歴から検索:",
                    "label.hotkey_plus_key" to "+ キー:",
                    "label.history_total" to "合計: %d 件",
                    "mode.release" to "キーを離したとき",
                    "mode.fly" to "リアルタイム入力",
                    "mode.direct" to "直接タイピング",
                    "mode.clipboard" to "クリップボード",
                    "placeholder.no_dictations" to "変換履歴がありません。ホットキーを押すか「話す」ボタンを押してください。",
                    "opt.audio.javasound" to "JavaSound (標準クロスプラットフォーム)",
                    "opt.audio.portaudio" to "PortAudio (ネイティブ代替)",
                    "opt.ins.direct" to "直接入力 (プライバシー保護)",
                    "opt.ins.clipboard" to "クリップボード貼り付け (Ctrl+V)",
                    "opt.timing.release" to "キー解放時 (デフォルト - 全フレーズ)",
                    "opt.timing.onthefly" to "リアルタイム (逐次入力)",
                    "opt.device.cpu" to "CPU (標準)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan)",
                    "lang.auto" to "自動検出 (auto)",
                    "lang.en" to "英語 (en)",
                    "lang.fr" to "フランス語 (fr)",
                    "lang.de" to "ドイツ語 (de)",
                    "lang.ru" to "ロシア語 (ru)",
                    "lang.ja" to "日本語 (ja)",
                    "lang.zh" to "中国語 (zh)",
                    "lang.tr" to "トルコ語 (tr)",
                    "lang.ar" to "アラビア語 (ar)",
                    "lang.es" to "スペイン語 (es)",
                    "lang.it" to "イタリア語 (it)",
                    "lang.pt" to "ポルトガル語 (pt)",
                    "lang.ko" to "韓国語 (ko)",
                    "lang.uk" to "ウクライナ語 (uk)",
                    "lang.pl" to "ポーランド語 (pl)",
                    "lang.nl" to "オランダ語 (nl)",
                    "check.bilingual" to "バイリンガルモード (EN + 選択言語)",
                    "check.copy_clipboard" to "文字起こしをクリップボードに保存",
                    "check.fallback_clipboard" to "入力先がない場合はクリップボードに保存",
                    "check.autostart" to "システムログイン時に自動起動",
                    "status.checking_binary" to "whisper-cli を確認中...",
                    "status.model_checking" to "状態: 確認中...",
                    "status.model_downloaded" to "状態: ダウンロード済み",
                    "status.model_not_found" to "状態: 未検出",
                    "label.model_status" to "モデルの状態:",
                    "label.download_progress" to "ダウンロード進行状況:",
                    "label.audio_file_dictation" to "音声ファイル書き起こし:",
                    "btn.redownload" to "再ダウンロード",
                    "btn.download" to "ダウンロード",
                    "tip.bilingual" to "英語と選択言語の混在コードスイッチングを許可",
                    "tip.download_cli" to "ビルド済み whisper-cli をダウンロード",
                    "tip.key_field" to "キー (例: L, F8, Space, Return)",
                    "tip.reset_defaults" to "すべての設定を初期値にリセット",
                    "tip.export" to "設定をYAMLファイルにエクスポート",
                    "tip.import" to "YAMLファイルから設定をインポート",
                    "metric.current_title" to "現在のテキスト",
                    "metric.history_mean_title" to "履歴の平均",
                    "metric.all_time_title" to "全期間",
                    "opt.trigger.hold" to "長押しで通話 (ホールド)",
                    "opt.trigger.toggle" to "オン/オフ切り替え (トグル)",
                    "label.trigger_mode" to "トリガーモード:",
                    "label.input_gain" to "マイクゲイン:",
                    "label.input_level" to "音声入力レベル:",
                    "btn.test_mic" to "マイクテスト",
                    "btn.stop_test" to "テスト停止",
                    "warning.silence" to "マイクがミュートまたは音量が小さすぎます",
                    "warning.clipping" to "音割れ（クリッピング）を検出；音量を下げてください",
                ),
            AppLanguage.CN to
                mapOf(
                    "tab.dashboard" to "仪表板",
                    "tab.settings" to "设置",
                    "tab.whisper" to "Whisper 与模型",
                    "tab.history" to "历史记录",
                    "tab.batch" to "批量转录",
                    "bulb.app.title" to "程序",
                    "bulb.app.active" to "运行中",
                    "bulb.voice.title" to "语音",
                    "bulb.voice.idle" to "待命",
                    "bulb.voice.listening" to "聆听中",
                    "bulb.voice.processing" to "处理中",
                    "bulb.voice.transcribing" to "识别中",
                    "bulb.mode.title" to "模式",
                    "btn.hold_to_speak" to "按住说话 (PTT)",
                    "btn.recording" to "录音中... 松开输入",
                    "btn.processing" to "语音处理中...",
                    "btn.copy" to "复制",
                    "btn.collapse" to "折叠至指示灯",
                    "btn.expand" to "展开窗口",
                    "btn.hide_tray" to "最小化至托盘",
                    "btn.exit" to "退出程序",
                    "btn.open_settings" to "打开设置...",
                    "btn.record_shortcut" to "录制快捷键",
                    "btn.apply" to "应用",
                    "btn.reset_defaults" to "恢复默认值",
                    "btn.export" to "导出设置...",
                    "btn.import" to "导入设置...",
                    "btn.download_binary" to "下载 whisper-cli",
                    "btn.browse" to "浏览...",
                    "btn.download_model" to "下载模型",
                    "btn.transcribe_file" to "转录音频文件...",
                    "btn.clear_history" to "清空历史",
                    "label.audio_provider" to "音频驱动:",
                    "label.microphone" to "麦克风 / 监听:",
                    "label.engine" to "识别引擎:",
                    "label.hotkey" to "语音快捷键:",
                    "label.insertion_mode" to "文本插入方式:",
                    "label.timing" to "插入时机:",
                    "label.clipboard_privacy" to "剪贴板隐私:",
                    "label.system_startup" to "开机自启:",
                    "label.whisper_exec" to "Whisper 可执行文件:",
                    "label.multilingual_model" to "多语言模型:",
                    "label.spoken_lang" to "说话语言:",
                    "label.bilingual_mode" to "双语模式:",
                    "label.inference_device" to "计算设备:",
                    "label.ui_language" to "界面语言:",
                    "label.recent_speech" to "最近转录内容:",
                    "label.search_history" to "搜索历史:",
                    "label.hotkey_plus_key" to "+ 按键:",
                    "label.history_total" to "共计: %d 条记录",
                    "mode.release" to "松开按键时",
                    "mode.fly" to "实时输入",
                    "mode.direct" to "直接按键模拟",
                    "mode.clipboard" to "剪贴板粘贴",
                    "placeholder.no_dictations" to "暂无听写记录。按住热键或点击开始说话。",
                    "opt.audio.javasound" to "JavaSound (标准跨平台)",
                    "opt.audio.portaudio" to "PortAudio (原生替代方案)",
                    "opt.ins.direct" to "直接键入 (隐私保护)",
                    "opt.ins.clipboard" to "剪贴板粘贴 (Ctrl+V)",
                    "opt.timing.release" to "按键释放时 (默认 - 完整短语)",
                    "opt.timing.onthefly" to "实时输入 (增量即时打字)",
                    "opt.device.cpu" to "CPU (标准)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan 加速)",
                    "lang.auto" to "自动检测 (auto)",
                    "lang.en" to "英语 (en)",
                    "lang.fr" to "法语 (fr)",
                    "lang.de" to "德语 (de)",
                    "lang.ru" to "俄语 (ru)",
                    "lang.ja" to "日语 (ja)",
                    "lang.zh" to "中文 (zh)",
                    "lang.tr" to "土耳其语 (tr)",
                    "lang.ar" to "阿拉伯语 (ar)",
                    "lang.es" to "西班牙语 (es)",
                    "lang.it" to "意大利语 (it)",
                    "lang.pt" to "葡萄牙语 (pt)",
                    "lang.ko" to "韩语 (ko)",
                    "lang.uk" to "乌克兰语 (uk)",
                    "lang.pl" to "波兰语 (pl)",
                    "lang.nl" to "荷兰语 (nl)",
                    "check.bilingual" to "双语模式 (英文 + 选定语言)",
                    "check.copy_clipboard" to "将转录内容保存至剪贴板",
                    "check.fallback_clipboard" to "无活动输入框时保存至剪贴板",
                    "check.autostart" to "系统登录时自动启动 GolosAI",
                    "status.checking_binary" to "检查 whisper-cli 中...",
                    "status.model_checking" to "状态: 检查中...",
                    "status.model_downloaded" to "状态: 已下载",
                    "status.model_not_found" to "状态: 未找到",
                    "label.model_status" to "模型状态:",
                    "label.download_progress" to "下载进度:",
                    "label.audio_file_dictation" to "音频文件听写:",
                    "btn.redownload" to "重新下载",
                    "btn.download" to "下载",
                    "tip.bilingual" to "允许英语与选定语言之间的混合代码切换",
                    "tip.download_cli" to "下载预编译的 whisper-cli 二进制文件",
                    "tip.key_field" to "按键 (例如 L, F8, Space, Return)",
                    "tip.reset_defaults" to "恢复所有设置为初始默认值",
                    "tip.export" to "导出设置到 YAML 文件",
                    "tip.import" to "从 YAML 文件导入设置",
                    "metric.current_title" to "当前文本",
                    "metric.history_mean_title" to "历史平均",
                    "metric.all_time_title" to "累计总计",
                    "opt.trigger.hold" to "按住说话 (长按)",
                    "opt.trigger.toggle" to "开关切换 (点击开始/停止)",
                    "label.trigger_mode" to "触发模式:",
                    "label.input_gain" to "麦克风增益:",
                    "label.input_level" to "音频输入电平:",
                    "btn.test_mic" to "测试麦克风",
                    "btn.stop_test" to "停止测试",
                    "warning.silence" to "麦克风静音或音量过低",
                    "warning.clipping" to "检测到音频削波；请降低输入音量",
                ),
            AppLanguage.TR to
                mapOf(
                    "tab.dashboard" to "Kontrol Paneli",
                    "tab.settings" to "Ayarlar",
                    "tab.whisper" to "Whisper ve Modeller",
                    "tab.history" to "Geçmiş",
                    "tab.batch" to "Toplu İşleme",
                    "bulb.app.title" to "UYG",
                    "bulb.app.active" to "AKTİF",
                    "bulb.voice.title" to "SES",
                    "bulb.voice.idle" to "BEKLEMEDE",
                    "bulb.voice.listening" to "DİNLİYOR",
                    "bulb.voice.processing" to "İŞLENİYOR",
                    "bulb.voice.transcribing" to "ÇEVRİLİYOR",
                    "bulb.mode.title" to "MOD",
                    "btn.hold_to_speak" to "Konuşmak İçin Basılı Tutun",
                    "btn.recording" to "Kaydediliyor... Bırakın",
                    "btn.processing" to "Ses işleniyor...",
                    "btn.copy" to "Kopyala",
                    "btn.collapse" to "Işıklara Küçült",
                    "btn.expand" to "Pencereyi Genişlet",
                    "btn.hide_tray" to "Sistem Tepsisine Küçült",
                    "btn.exit" to "Uygulamadan Çık",
                    "btn.open_settings" to "Ayarları Aç...",
                    "btn.record_shortcut" to "Kısayol Kaydet",
                    "btn.apply" to "Uygula",
                    "btn.reset_defaults" to "Varsayılana Sıfırla",
                    "btn.export" to "Ayarları Dışa Aktar...",
                    "btn.import" to "Ayarları İçe Aktar...",
                    "btn.download_binary" to "whisper-cli İndir",
                    "btn.browse" to "Gözat...",
                    "btn.download_model" to "Modeli İndir",
                    "btn.transcribe_file" to "Ses Dosyasını Çevir...",
                    "btn.clear_history" to "Geçmişi Temizle",
                    "label.audio_provider" to "Ses Sağlayıcı:",
                    "label.microphone" to "Ses Girişi / Monitör:",
                    "label.engine" to "Tanıma Motoru:",
                    "label.hotkey" to "Bas-Konuş Kısayolu:",
                    "label.insertion_mode" to "Metin Ekleme Modu:",
                    "label.timing" to "Ekleme Zamanı:",
                    "label.clipboard_privacy" to "Pano Gizliliği:",
                    "label.system_startup" to "Sistem Başlangıcı:",
                    "label.whisper_exec" to "Whisper Yürütülebilir:",
                    "label.multilingual_model" to "Çok Dilli Model:",
                    "label.spoken_lang" to "Konuşulan Dil:",
                    "label.bilingual_mode" to "İki Dilli Mod:",
                    "label.inference_device" to "İşlem Birimi:",
                    "label.ui_language" to "Arayüz Dili:",
                    "label.recent_speech" to "Son Konuşma Metni:",
                    "label.search_history" to "Geçmişte Ara:",
                    "label.hotkey_plus_key" to "+ Tuş:",
                    "label.history_total" to "Toplam: %d kayıt",
                    "mode.release" to "Tuş Bırakıldığında",
                    "mode.fly" to "Anlık Yazım",
                    "mode.direct" to "Doğrudan Yazma",
                    "mode.clipboard" to "Pano ile Yapıştırma",
                    "placeholder.no_dictations" to "Henüz dikte yok. Kısayol tuşunu basılı tutun veya Konuş'a basın.",
                    "opt.audio.javasound" to "JavaSound (Çapraz Platform Standardı)",
                    "opt.audio.portaudio" to "PortAudio (Alternatif Yerel Sürücü)",
                    "opt.ins.direct" to "Doğrudan Yazma (Gizlilik Odaklı)",
                    "opt.ins.clipboard" to "Panoya Yapıştır (Ctrl+V)",
                    "opt.timing.release" to "Tuş Bırakıldığında (Varsayılan - Tüm Cümle)",
                    "opt.timing.onthefly" to "Anlık Yazım (Canlı Kademeli Yazma)",
                    "opt.device.cpu" to "CPU (Standart)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan)",
                    "lang.auto" to "Otomatik Algıla (auto)",
                    "lang.en" to "İngilizce (en)",
                    "lang.fr" to "Fransızca (fr)",
                    "lang.de" to "Almanca (de)",
                    "lang.ru" to "Rusça (ru)",
                    "lang.ja" to "Japonca (ja)",
                    "lang.zh" to "Çince (zh)",
                    "lang.tr" to "Türkçe (tr)",
                    "lang.ar" to "Arapça (ar)",
                    "lang.es" to "İspanyolca (es)",
                    "lang.it" to "İtalyanca (it)",
                    "lang.pt" to "Portekizce (pt)",
                    "lang.ko" to "Korece (ko)",
                    "lang.uk" to "Ukraynaca (uk)",
                    "lang.pl" to "Lehçe (pl)",
                    "lang.nl" to "Felemenkçe (nl)",
                    "check.bilingual" to "İki Dilli Mod (EN + Seçilen Dil)",
                    "check.copy_clipboard" to "Metni panoya kopyala",
                    "check.fallback_clipboard" to "Etkin alan yoksa panoya kaydet",
                    "check.autostart" to "GolosAI'yi sistem açılışında başlat",
                    "status.checking_binary" to "whisper-cli kontrol ediliyor...",
                    "status.model_checking" to "Durum: Kontrol ediliyor...",
                    "status.model_downloaded" to "Durum: İndirildi",
                    "status.model_not_found" to "Durum: Bulunamadı",
                    "label.model_status" to "Model Durumu:",
                    "label.download_progress" to "İndirme İlerlemesi:",
                    "label.audio_file_dictation" to "Ses Dosyası Dikte:",
                    "btn.redownload" to "Yeniden İndir",
                    "btn.download" to "İndir",
                    "tip.bilingual" to "İngilizce ile seçilen dil arasında karışık geçişe izin verir",
                    "tip.download_cli" to "Derlenmiş whisper-cli ikili dosyasını indir",
                    "tip.key_field" to "Tuş (örn. L, F8, Space, Return)",
                    "tip.reset_defaults" to "Tüm ayarları varsayılanlara sıfırla",
                    "tip.export" to "Ayarları YAML dosyasına aktar",
                    "tip.import" to "Ayarları YAML dosyasından yükle",
                    "metric.current_title" to "GEÇERLİ METİN",
                    "metric.history_mean_title" to "GEÇMİŞ ORTALAMASI",
                    "metric.all_time_title" to "TÜM ZAMANLAR",
                    "opt.trigger.hold" to "Konuşmak İçin Basılı Tut",
                    "opt.trigger.toggle" to "Aç/Kapat Geçişi",
                    "label.trigger_mode" to "Tetikleme Modu:",
                    "label.input_gain" to "Mikrofon Kazancı:",
                    "label.input_level" to "Ses Giriş Seviyesi:",
                    "btn.test_mic" to "Mikrofonu Test Et",
                    "btn.stop_test" to "Testi Durdur",
                    "warning.silence" to "Mikrofon sessizde veya ses çok düşük",
                    "warning.clipping" to "Ses kırpılması tespit edildi; giriş seviyesini düşürün",
                ),
            AppLanguage.AR to
                mapOf(
                    "tab.dashboard" to "لوحة التحكم",
                    "tab.settings" to "الإعدادات",
                    "tab.whisper" to "Whisper والنماذج",
                    "tab.history" to "السجل",
                    "tab.batch" to "المعالجة الدفعية",
                    "bulb.app.title" to "التطبيق",
                    "bulb.app.active" to "نشط",
                    "bulb.voice.title" to "الصوت",
                    "bulb.voice.idle" to "خامل",
                    "bulb.voice.listening" to "استماع",
                    "bulb.voice.processing" to "معالجة",
                    "bulb.voice.transcribing" to "تحويل",
                    "bulb.mode.title" to "الوضع",
                    "btn.hold_to_speak" to "اضغط مطولاً للتحدث",
                    "btn.recording" to "جارٍ التسجيل... اترك للإدخال",
                    "btn.processing" to "جارٍ معالجة الصوت...",
                    "btn.copy" to "نسخ",
                    "btn.collapse" to "تصغير إلى المصابيح",
                    "btn.expand" to "توسيع النافذة",
                    "btn.hide_tray" to "إخفاء في شريط المهام",
                    "btn.exit" to "إنهاء التطبيق",
                    "btn.open_settings" to "فتح الإعدادات...",
                    "btn.record_shortcut" to "تسجيل اختصار لوحة المفاتيح",
                    "btn.apply" to "تطبيق",
                    "btn.reset_defaults" to "إعادة التعيين إلى الافتراضي",
                    "btn.export" to "تصدير الإعدادات...",
                    "btn.import" to "استيراد الإعدادات...",
                    "btn.download_binary" to "تنزيل whisper-cli",
                    "btn.browse" to "استعراض...",
                    "btn.download_model" to "تنزيل النموذج",
                    "btn.transcribe_file" to "تحويل ملف صوتي...",
                    "btn.clear_history" to "مسح السجل",
                    "label.audio_provider" to "مزود الصوت:",
                    "label.microphone" to "الميكروفون / المراقبة:",
                    "label.engine" to "محرك التعرف:",
                    "label.hotkey" to "مفتاح التحدث المباشر:",
                    "label.insertion_mode" to "طريقة إدخال النص:",
                    "label.timing" to "توقيت الإدخال:",
                    "label.clipboard_privacy" to "خصوصية الحافظة:",
                    "label.system_startup" to "بدء التشغيل مع النظام:",
                    "label.whisper_exec" to "ملف تشغيل Whisper:",
                    "label.multilingual_model" to "النموذج متعدد اللغات:",
                    "label.spoken_lang" to "لغة التحدث:",
                    "label.bilingual_mode" to "الوضع ثنائي اللغة:",
                    "label.inference_device" to "جهاز المعالجة:",
                    "label.ui_language" to "لغة الواجهة:",
                    "label.recent_speech" to "آخر نص محول:",
                    "label.search_history" to "بحث في السجل:",
                    "label.hotkey_plus_key" to "+ المفتاح:",
                    "label.history_total" to "المجموع: %d عنصر",
                    "mode.release" to "عند إفلات المفتاح",
                    "mode.fly" to "مباشر أثناء الكلام",
                    "mode.direct" to "كتابة مباشرة",
                    "mode.clipboard" to "عبر الحافظة",
                    "placeholder.no_dictations" to "لا توجد تسجيلات حتى الآن. اضغط مطولاً على مفتاح الاختصار أو اضغط على تحدث.",
                    "opt.audio.javasound" to "JavaSound (القياسي عبر المنصات)",
                    "opt.audio.portaudio" to "PortAudio (بديل أصلي)",
                    "opt.ins.direct" to "كتابة مباشرة (حفظ الخصوصية)",
                    "opt.ins.clipboard" to "لصق الحافظة (Ctrl+V)",
                    "opt.timing.release" to "عند إفلات المفتاح (افتراضي - العبارة كاملة)",
                    "opt.timing.onthefly" to "مباشر أثناء الكلام (كتابة تدريجية)",
                    "opt.device.cpu" to "CPU (قياسي)",
                    "opt.device.gpu" to "GPU (تسريع عتادي)",
                    "lang.auto" to "اكتشاف تلقائي (auto)",
                    "lang.en" to "الإنجليزية (en)",
                    "lang.fr" to "الفرنسية (fr)",
                    "lang.de" to "الألمانية (de)",
                    "lang.ru" to "الروسية (ru)",
                    "lang.ja" to "اليابانية (ja)",
                    "lang.zh" to "الصينية (zh)",
                    "lang.tr" to "التركية (tr)",
                    "lang.ar" to "العربية (ar)",
                    "lang.es" to "الإسبانية (es)",
                    "lang.it" to "الإيطالية (it)",
                    "lang.pt" to "البرتغالية (pt)",
                    "lang.ko" to "الكورية (ko)",
                    "lang.uk" to "الأوكرانية (uk)",
                    "lang.pl" to "البولندية (pl)",
                    "lang.nl" to "الهولندية (nl)",
                    "check.bilingual" to "الوضع ثنائي اللغة (EN + اللغة المحددة)",
                    "check.copy_clipboard" to "حفظ النص المحول في الحافظة",
                    "check.fallback_clipboard" to "حفظ في الحافظة إذا لم يكن هناك حقل إدخال",
                    "check.autostart" to "تشغيل GolosAI تلقائياً عند تسجيل الدخول",
                    "status.checking_binary" to "جارٍ فحص whisper-cli...",
                    "status.model_checking" to "الحالة: جارٍ الفحص...",
                    "status.model_downloaded" to "الحالة: تم التنزيل",
                    "status.model_not_found" to "الحالة: غير موجود",
                    "label.model_status" to "حالة النموذج:",
                    "label.download_progress" to "تقدم التنزيل:",
                    "label.audio_file_dictation" to "إملاء الملف الصوتي:",
                    "btn.redownload" to "إعادة التنزيل",
                    "btn.download" to "تنزيل",
                    "tip.bilingual" to "السماح بالتبديل اللغوي بين الإنجليزية واللغة المحددة",
                    "tip.download_cli" to "تنزيل برنامج whisper-cli مسبق الترجمة",
                    "tip.key_field" to "المفتاح (مثال: L, F8, Space, Return)",
                    "tip.reset_defaults" to "استعادة الإعدادات الافتراضية الأولية",
                    "tip.export" to "تصدير الإعدادات إلى ملف YAML",
                    "tip.import" to "استيراد الإعدادات من ملف YAML",
                    "metric.current_title" to "النص الحالي",
                    "metric.history_mean_title" to "متوسط السجل",
                    "metric.all_time_title" to "كل الأوقات",
                    "opt.trigger.hold" to "اضغط مطولاً للتحدث",
                    "opt.trigger.toggle" to "تبديل تشغيل/إيقاف",
                    "label.trigger_mode" to "وضع التنشيط:",
                    "label.input_gain" to "مستوى تضخيم الميكروفون:",
                    "label.input_level" to "مستوى إدخال الصوت:",
                    "btn.test_mic" to "اختبار الميكروفون",
                    "btn.stop_test" to "إيقاف الاختبار",
                    "warning.silence" to "الميكروفون مكتوم أو مستوى الصوت منخفض للغاية",
                    "warning.clipping" to "تم اكتشاف تقطيع في الصوت؛ يرجى خفض مستوى الصوت",
                ),
            AppLanguage.ES to
                mapOf(
                    "tab.dashboard" to "Panel",
                    "tab.settings" to "Configuración",
                    "tab.whisper" to "Whisper y Modelos",
                    "tab.history" to "Historial",
                    "tab.batch" to "Procesamiento por lotes",
                    "bulb.app.title" to "APP",
                    "bulb.app.active" to "ACTIVO",
                    "bulb.voice.title" to "VOZ",
                    "bulb.voice.idle" to "EN ESPERA",
                    "bulb.voice.listening" to "ESCUCHANDO",
                    "bulb.voice.processing" to "PROCESANDO",
                    "bulb.voice.transcribing" to "TRANSCRIBIENDO",
                    "bulb.mode.title" to "MODO",
                    "btn.hold_to_speak" to "Mantenga para hablar",
                    "btn.recording" to "Grabando... Suelte para insertar",
                    "btn.processing" to "Procesando voz...",
                    "btn.copy" to "Copiar",
                    "btn.collapse" to "Minimizar a indicadores",
                    "btn.expand" to "Expandir ventana",
                    "btn.hide_tray" to "Minimizar a la bandeja",
                    "btn.exit" to "Salir",
                    "btn.open_settings" to "Abrir configuración...",
                    "btn.record_shortcut" to "Grabar atajo",
                    "btn.apply" to "Aplicar",
                    "btn.reset_defaults" to "Restablecer valores",
                    "btn.export" to "Exportar configuración...",
                    "btn.import" to "Importar configuración...",
                    "btn.download_binary" to "Descargar whisper-cli",
                    "btn.browse" to "Examinar...",
                    "btn.download_model" to "Descargar modelo",
                    "btn.transcribe_file" to "Transcribir archivo...",
                    "btn.clear_history" to "Borrar historial",
                    "label.audio_provider" to "Proveedor de audio:",
                    "label.microphone" to "Entrada de audio / Monitor:",
                    "label.engine" to "Motor de reconocimiento:",
                    "label.hotkey" to "Atajo Push-to-Talk:",
                    "label.insertion_mode" to "Modo de inserción:",
                    "label.timing" to "Momento de inserción:",
                    "label.clipboard_privacy" to "Privacidad portapapeles:",
                    "label.system_startup" to "Inicio del sistema:",
                    "label.whisper_exec" to "Ejecutable Whisper:",
                    "label.multilingual_model" to "Modelo multilingüe:",
                    "label.spoken_lang" to "Idioma hablado:",
                    "label.bilingual_mode" to "Modo bilingüe:",
                    "label.inference_device" to "Dispositivo de inferencia:",
                    "label.ui_language" to "Idioma de interfaz:",
                    "label.recent_speech" to "Transcripción reciente:",
                    "label.search_history" to "Buscar en historial:",
                    "label.hotkey_plus_key" to "+ Tecla:",
                    "label.history_total" to "Total: %d entradas",
                    "mode.release" to "Al soltar la tecla",
                    "mode.fly" to "En tiempo real",
                    "mode.direct" to "Escritura directa",
                    "mode.clipboard" to "Portapapeles",
                    "placeholder.no_dictations" to "No hay dictados todavía. Presione Hablar o use su atajo.",
                    "opt.audio.javasound" to "JavaSound (Estándar multiplataforma)",
                    "opt.audio.portaudio" to "PortAudio (Nativo alternativo)",
                    "opt.ins.direct" to "Escritura directa (Privacidad)",
                    "opt.ins.clipboard" to "Pegar del portapapeles (Ctrl+V)",
                    "opt.timing.release" to "Al soltar la tecla (Predeterminado - Frase completa)",
                    "opt.timing.onthefly" to "En tiempo real (Escritura incremental)",
                    "opt.device.cpu" to "CPU (Estándar)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan)",
                    "lang.auto" to "Detección automática (auto)",
                    "lang.en" to "Inglés (en)",
                    "lang.fr" to "Francés (fr)",
                    "lang.de" to "Alemán (de)",
                    "lang.ru" to "Ruso (ru)",
                    "lang.ja" to "Japonés (ja)",
                    "lang.zh" to "Chino (zh)",
                    "lang.tr" to "Turco (tr)",
                    "lang.ar" to "Árabe (ar)",
                    "lang.es" to "Español (es)",
                    "lang.it" to "Italiano (it)",
                    "lang.pt" to "Portugués (pt)",
                    "lang.ko" to "Coreano (ko)",
                    "lang.uk" to "Ucraniano (uk)",
                    "lang.pl" to "Polaco (pl)",
                    "lang.nl" to "Holandés (nl)",
                    "check.bilingual" to "Modo bilingüe (EN + Idioma seleccionado)",
                    "check.copy_clipboard" to "Guardar transcripción en portapapeles",
                    "check.fallback_clipboard" to "Al portapapeles si no hay campo enfocado",
                    "check.autostart" to "Iniciar GolosAI al iniciar sesión",
                    "status.checking_binary" to "Comprobando whisper-cli...",
                    "status.model_checking" to "Estado: Comprobando...",
                    "status.model_downloaded" to "Estado: Descargado",
                    "status.model_not_found" to "Estado: No encontrado",
                    "label.model_status" to "Estado del modelo:",
                    "label.download_progress" to "Progreso de descarga:",
                    "label.audio_file_dictation" to "Dictado de archivo de audio:",
                    "btn.redownload" to "Volver a descargar",
                    "btn.download" to "Descargar",
                    "tip.bilingual" to "Permite alternar código entre inglés y el idioma seleccionado",
                    "tip.download_cli" to "Descargar ejecutable whisper-cli precompilado",
                    "tip.key_field" to "Tecla (ej. L, F8, Espacio, Intro)",
                    "tip.reset_defaults" to "Restablecer todos los ajustes predeterminados",
                    "tip.export" to "Exportar ajustes a archivo YAML",
                    "tip.import" to "Importar ajustes desde archivo YAML",
                    "metric.current_title" to "TEXTO ACTUAL",
                    "metric.history_mean_title" to "MEDIA HISTORIAL",
                    "metric.all_time_title" to "TIEMPO TOTAL",
                    "opt.trigger.hold" to "Mantener para hablar",
                    "opt.trigger.toggle" to "Alternar encendido/apagado",
                    "label.trigger_mode" to "Modo de activación:",
                    "label.input_gain" to "Ganancia del micrófono:",
                    "label.input_level" to "Nivel de entrada de audio:",
                    "btn.test_mic" to "Probar micrófono",
                    "btn.stop_test" to "Detener prueba",
                    "warning.silence" to "Micrófono silenciado o volumen demasiado bajo",
                    "warning.clipping" to "Saturación de audio detectada; baje el volumen",
                ),
            AppLanguage.IT to
                mapOf(
                    "tab.dashboard" to "Pannello",
                    "tab.settings" to "Impostazioni",
                    "tab.whisper" to "Whisper & Modelli",
                    "tab.history" to "Cronologia",
                    "tab.batch" to "Elaborazione batch",
                    "bulb.app.title" to "APP",
                    "bulb.app.active" to "ATTIVO",
                    "bulb.voice.title" to "VOCE",
                    "bulb.voice.idle" to "IN ATTESA",
                    "bulb.voice.listening" to "IN ASCOLTO",
                    "bulb.voice.processing" to "ELABORAZIONE",
                    "bulb.voice.transcribing" to "TRASCRIZIONE",
                    "bulb.mode.title" to "MODO",
                    "btn.hold_to_speak" to "Tieni premuto per parlare",
                    "btn.recording" to "Registrazione... Rilascia",
                    "btn.processing" to "Elaborazione voce...",
                    "btn.copy" to "Copia",
                    "btn.collapse" to "Riduci a spie luminose",
                    "btn.expand" to "Espandi finestra",
                    "btn.hide_tray" to "Riduci nella barra",
                    "btn.exit" to "Esci",
                    "btn.open_settings" to "Apri impostazioni...",
                    "btn.record_shortcut" to "Registra scorciatoia",
                    "btn.apply" to "Applica",
                    "btn.reset_defaults" to "Ripristina predefiniti",
                    "btn.export" to "Esporta impostazioni...",
                    "btn.import" to "Importa impostazioni...",
                    "btn.download_binary" to "Scarica whisper-cli",
                    "btn.browse" to "Sfoglia...",
                    "btn.download_model" to "Scarica modello",
                    "btn.transcribe_file" to "Trascrivi file audio...",
                    "btn.clear_history" to "Cancella cronologia",
                    "label.audio_provider" to "Provider audio:",
                    "label.microphone" to "Microfono / Monitor:",
                    "label.engine" to "Motore di riconoscimento:",
                    "label.hotkey" to "Scorciatoia Push-to-Talk:",
                    "label.insertion_mode" to "Modalità inserimento:",
                    "label.timing" to "Tempistica inserimento:",
                    "label.clipboard_privacy" to "Privacy appunti:",
                    "label.system_startup" to "Avvio di sistema:",
                    "label.whisper_exec" to "Eseguibile Whisper:",
                    "label.multilingual_model" to "Modello multilingue:",
                    "label.spoken_lang" to "Lingua parlata:",
                    "label.bilingual_mode" to "Modalità bilingue:",
                    "label.inference_device" to "Dispositivo di calcolo:",
                    "label.ui_language" to "Lingua interfaccia:",
                    "label.recent_speech" to "Trascrizione recente:",
                    "label.search_history" to "Cerca nella cronologia:",
                    "label.hotkey_plus_key" to "+ Tasto:",
                    "label.history_total" to "Totale: %d voci",
                    "mode.release" to "Al rilascio tasto",
                    "mode.fly" to "In tempo reale",
                    "mode.direct" to "Digitazione diretta",
                    "mode.clipboard" to "Appunti",
                    "placeholder.no_dictations" to "Nessuna dettatura. Tieni premuto il tasto di scelta rapida o premi Parla.",
                    "opt.audio.javasound" to "JavaSound (Standard multipiattaforma)",
                    "opt.audio.portaudio" to "PortAudio (Nativo alternativo)",
                    "opt.ins.direct" to "Digitazione diretta (Privacy)",
                    "opt.ins.clipboard" to "Incolla dagli appunti (Ctrl+V)",
                    "opt.timing.release" to "Al rilascio del tasto (Predefinito - Frase intera)",
                    "opt.timing.onthefly" to "In tempo reale (Digitazione incrementale)",
                    "opt.device.cpu" to "CPU (Standard)",
                    "opt.device.gpu" to "GPU (CUDA / Metal / Vulkan)",
                    "lang.auto" to "Rilevamento automatico (auto)",
                    "lang.en" to "Inglese (en)",
                    "lang.fr" to "Francese (fr)",
                    "lang.de" to "Tedesco (de)",
                    "lang.ru" to "Russo (ru)",
                    "lang.ja" to "Giapponese (ja)",
                    "lang.zh" to "Cinese (zh)",
                    "lang.tr" to "Turco (tr)",
                    "lang.ar" to "Arabo (ar)",
                    "lang.es" to "Spagnolo (es)",
                    "lang.it" to "Italiano (it)",
                    "lang.pt" to "Portoghese (pt)",
                    "lang.ko" to "Coreano (ko)",
                    "lang.uk" to "Ucraino (uk)",
                    "lang.pl" to "Polacco (pl)",
                    "lang.nl" to "Olandese (nl)",
                    "check.bilingual" to "Modalità bilingue (EN + Lingua selezionata)",
                    "check.copy_clipboard" to "Salva trascrizione negli appunti",
                    "check.fallback_clipboard" to "Negli appunti se nessun campo attivo",
                    "check.autostart" to "Avvia GolosAI all'accesso al sistema",
                    "status.checking_binary" to "Verifica di whisper-cli in corso...",
                    "status.model_checking" to "Stato: Verifica in corso...",
                    "status.model_downloaded" to "Stato: Scaricato",
                    "status.model_not_found" to "Stato: Non trovato",
                    "label.model_status" to "Stato del modello:",
                    "label.download_progress" to "Avanzamento del download:",
                    "label.audio_file_dictation" to "Dettatura file audio:",
                    "btn.redownload" to "Riscarica",
                    "btn.download" to "Scarica",
                    "tip.bilingual" to "Consente alternanza di codice tra inglese e lingua selezionata",
                    "tip.download_cli" to "Scarica il binario whisper-cli precompilato",
                    "tip.key_field" to "Tasto (es. L, F8, Spazio, Invio)",
                    "tip.reset_defaults" to "Ripristina tutte le impostazioni predefinite",
                    "tip.export" to "Esporta impostazioni in file YAML",
                    "tip.import" to "Importa impostazioni da file YAML",
                    "metric.current_title" to "TESTO CORRENTE",
                    "metric.history_mean_title" to "MEDIA CRONOLOGIA",
                    "metric.all_time_title" to "TUTTO IL TEMPO",
                    "opt.trigger.hold" to "Tieni premuto per parlare",
                    "opt.trigger.toggle" to "Attiva/Disattiva",
                    "label.trigger_mode" to "Modalità attivazione:",
                    "label.input_gain" to "Guadagno microfono:",
                    "label.input_level" to "Livello ingresso audio:",
                    "btn.test_mic" to "Testa microfono",
                    "btn.stop_test" to "Interrompi test",
                    "warning.silence" to "Microfono disattivato o volume troppo basso",
                    "warning.clipping" to "Rilevato clipping audio; abbassare il volume",
                ),
        )

    fun tr(key: String): String {
        return translations[currentLanguage]?.get(key)
            ?: translations[AppLanguage.EN]?.get(key)
            ?: key
    }
}
