package su.kamil.dev.golos.app.ui

import java.util.concurrent.CopyOnWriteArrayList

enum class AppLanguage(val code: String, val displayName: String) {
    EN("en", "English"),
    FR("fr", "Français (French)"),
    DE("de", "Deutsch (German)"),
    RU("ru", "Русский (Russian)"),
    JP("ja", "日本語 (Japanese)"),
    CN("zh", "中文 (Chinese)"),
    TR("tr", "Türkçe (Turkish)"),
    AR("ar", "العربية (Arabic)"),
    ES("es", "Español (Spanish)"),
    IT("it", "Italiano (Italian)"),
    ;

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: EN
        }
    }
}

object AppLocalization {
    var currentLanguage: AppLanguage = AppLanguage.EN
        private set

    private val listeners = CopyOnWriteArrayList<() -> Unit>()

    fun setLanguage(lang: AppLanguage) {
        if (currentLanguage != lang) {
            currentLanguage = lang
            listeners.forEach { it.invoke() }
        }
    }

    fun addLanguageChangeListener(listener: () -> Unit) {
        listeners.add(listener)
    }

    private val translations =
        mapOf(
            AppLanguage.EN to
                mapOf(
                    "tab.dashboard" to "Dashboard",
                    "tab.settings" to "Settings",
                    "tab.whisper" to "Whisper & Models",
                    "tab.history" to "History",
                    "bulb.app.title" to "APP",
                    "bulb.app.active" to "ACTIVE",
                    "bulb.voice.title" to "VOICE",
                    "bulb.voice.idle" to "IDLE",
                    "bulb.voice.listening" to "LISTENING",
                    "bulb.voice.processing" to "PROCESSING",
                    "bulb.voice.transcribing" to "TRANSCRIBING",
                    "bulb.mode.title" to "MODE",
                    "btn.hold_to_speak" to "Hold to Speak (Push to Talk)",
                    "btn.recording" to "Recording... Release to transcribe",
                    "btn.processing" to "Processing speech...",
                    "btn.copy" to "Copy",
                    "btn.collapse" to "Collapse to Bulbs",
                    "btn.expand" to "Expand Window",
                    "btn.hide_tray" to "Hide to Tray",
                    "btn.exit" to "Exit Application",
                    "btn.open_settings" to "Open Settings...",
                    "btn.record_shortcut" to "Record Shortcut (Click & Press Keys)",
                    "btn.apply" to "Apply",
                    "btn.reset_defaults" to "Reset to Defaults",
                    "btn.export" to "Export Settings...",
                    "btn.import" to "Import Settings...",
                    "btn.download_binary" to "Download whisper-cli",
                    "btn.browse" to "Browse...",
                    "btn.download_model" to "Download Model",
                    "btn.transcribe_file" to "Transcribe Audio File...",
                    "btn.clear_history" to "Clear History",
                    "label.audio_provider" to "Audio Provider:",
                    "label.microphone" to "Audio Input / Monitor:",
                    "label.engine" to "Recognition Engine:",
                    "label.hotkey" to "Push-to-Talk Hotkey:",
                    "label.insertion_mode" to "Text Insertion Mode:",
                    "label.timing" to "Insertion Timing:",
                    "label.clipboard_privacy" to "Clipboard Privacy:",
                    "label.system_startup" to "System Startup:",
                    "label.whisper_exec" to "Whisper Executable:",
                    "label.multilingual_model" to "Multilingual Model:",
                    "label.spoken_lang" to "Spoken Language:",
                    "label.bilingual_mode" to "Bilingual Mode (EN + Selected Language)",
                    "label.inference_device" to "Inference Device:",
                    "label.ui_language" to "Interface Language:",
                    "label.recent_speech" to "Recent Speech Transcription:",
                    "label.search_history" to "Search History:",
                    "mode.release" to "On Key Release",
                    "mode.fly" to "On the Fly",
                    "mode.direct" to "Direct Typing",
                    "mode.clipboard" to "Clipboard",
                    "placeholder.no_dictations" to "No dictations yet. Hold your hotkey or press Hold to Speak.",
                ),
            AppLanguage.FR to
                mapOf(
                    "tab.dashboard" to "Tableau de bord",
                    "tab.settings" to "Paramètres",
                    "tab.whisper" to "Whisper et Modèles",
                    "tab.history" to "Historique",
                    "bulb.app.title" to "APPLI",
                    "bulb.app.active" to "ACTIF",
                    "bulb.voice.title" to "VOIX",
                    "bulb.voice.idle" to "EN ATTENTE",
                    "bulb.voice.listening" to "ÉCOUTE",
                    "bulb.voice.processing" to "TRAITEMENT",
                    "bulb.voice.transcribing" to "TRANSCRIPTION",
                    "bulb.mode.title" to "MODE",
                    "btn.hold_to_speak" to "Maintenir pour parler",
                    "btn.recording" to "Enregistrement... Relâchez",
                    "btn.processing" to "Traitement de la voix...",
                    "btn.copy" to "Copier",
                    "btn.collapse" to "Réduire aux voyants",
                    "btn.expand" to "Agrandir",
                    "btn.hide_tray" to "Réduire dans la barre",
                    "btn.exit" to "Quitter l'application",
                    "btn.open_settings" to "Paramètres...",
                    "btn.record_shortcut" to "Enregistrer un raccourci",
                    "btn.apply" to "Appliquer",
                    "btn.reset_defaults" to "Réinitialiser",
                    "btn.export" to "Exporter les paramètres...",
                    "btn.import" to "Importer les paramètres...",
                    "btn.download_binary" to "Télécharger whisper-cli",
                    "btn.browse" to "Parcourir...",
                    "btn.download_model" to "Télécharger le modèle",
                    "btn.transcribe_file" to "Transcrire un fichier audio...",
                    "btn.clear_history" to "Effacer l'historique",
                    "label.audio_provider" to "Fournisseur audio:",
                    "label.microphone" to "Entrée audio / Moniteur:",
                    "label.engine" to "Moteur de reconnaissance:",
                    "label.hotkey" to "Raccourci push-to-talk:",
                    "label.insertion_mode" to "Mode d'insertion de texte:",
                    "label.timing" to "Moment d'insertion:",
                    "label.clipboard_privacy" to "Confidentialité presse-papiers:",
                    "label.system_startup" to "Démarrage système:",
                    "label.whisper_exec" to "Exécutable Whisper:",
                    "label.multilingual_model" to "Modèle multilingue:",
                    "label.spoken_lang" to "Langue parlée:",
                    "label.bilingual_mode" to "Mode bilingue (EN + Langue sélectionnée)",
                    "label.inference_device" to "Périphérique de calcul:",
                    "label.ui_language" to "Langue de l'interface:",
                    "label.recent_speech" to "Transcription vocale récente:",
                    "label.search_history" to "Rechercher dans l'historique:",
                    "mode.release" to "Au relâchement",
                    "mode.fly" to "À la volée",
                    "mode.direct" to "Saisie directe",
                    "mode.clipboard" to "Presse-papiers",
                    "placeholder.no_dictations" to "Aucune dictée pour le moment. Maintenez le raccourci ou appuyez sur Parler.",
                ),
            AppLanguage.DE to
                mapOf(
                    "tab.dashboard" to "Übersicht",
                    "tab.settings" to "Einstellungen",
                    "tab.whisper" to "Whisper & Modelle",
                    "tab.history" to "Verlauf",
                    "bulb.app.title" to "APP",
                    "bulb.app.active" to "AKTIV",
                    "bulb.voice.title" to "STIMME",
                    "bulb.voice.idle" to "BEREIT",
                    "bulb.voice.listening" to "HÖRT ZU",
                    "bulb.voice.processing" to "VERARBEITUNG",
                    "bulb.voice.transcribing" to "TRANSKRIPTION",
                    "bulb.mode.title" to "MODUS",
                    "btn.hold_to_speak" to "Halten zum Sprechen",
                    "btn.recording" to "Aufnahme... Loslassen",
                    "btn.processing" to "Sprachverarbeitung...",
                    "btn.copy" to "Kopieren",
                    "btn.collapse" to "Auf Leuchten minimieren",
                    "btn.expand" to "Fenster vergrößern",
                    "btn.hide_tray" to "In Infobereich minimieren",
                    "btn.exit" to "Beenden",
                    "btn.open_settings" to "Einstellungen...",
                    "btn.record_shortcut" to "Tastenkombination aufnehmen",
                    "btn.apply" to "Anwenden",
                    "btn.reset_defaults" to "Auf Standard zurücksetzen",
                    "btn.export" to "Einstellungen exportieren...",
                    "btn.import" to "Einstellungen importieren...",
                    "btn.download_binary" to "whisper-cli herunterladen",
                    "btn.browse" to "Durchsuchen...",
                    "btn.download_model" to "Modell herunterladen",
                    "btn.transcribe_file" to "Audiodatei transkribieren...",
                    "btn.clear_history" to "Verlauf löschen",
                    "label.audio_provider" to "Audio-Anbieter:",
                    "label.microphone" to "Audioeingang / Monitor:",
                    "label.engine" to "Erkennungs-Engine:",
                    "label.hotkey" to "Push-to-Talk Hotkey:",
                    "label.insertion_mode" to "Texteinfügemodus:",
                    "label.timing" to "Einfügezeitpunkt:",
                    "label.clipboard_privacy" to "Zwischenablage-Datenschutz:",
                    "label.system_startup" to "Systemstart:",
                    "label.whisper_exec" to "Whisper-Programm:",
                    "label.multilingual_model" to "Mehrsprachiges Modell:",
                    "label.spoken_lang" to "Gesprochene Sprache:",
                    "label.bilingual_mode" to "Bilingualer Modus (EN + Ausgewählte Sprache)",
                    "label.inference_device" to "Inferenzgerät:",
                    "label.ui_language" to "Oberflächensprache:",
                    "label.recent_speech" to "Letzte Sprachtranskription:",
                    "label.search_history" to "Verlauf durchsuchen:",
                    "mode.release" to "Beim Loslassen",
                    "mode.fly" to "In Echtzeit",
                    "mode.direct" to "Direkte Eingabe",
                    "mode.clipboard" to "Zwischenablage",
                    "placeholder.no_dictations" to "Noch keine Diktate. Halten Sie Ihren Hotkey oder drücken Sie Sprechen.",
                ),
            AppLanguage.RU to
                mapOf(
                    "tab.dashboard" to "Панель управления",
                    "tab.settings" to "Настройки",
                    "tab.whisper" to "Whisper и Модели",
                    "tab.history" to "История",
                    "bulb.app.title" to "ПРИЛ",
                    "bulb.app.active" to "АКТИВНО",
                    "bulb.voice.title" to "ГОЛОС",
                    "bulb.voice.idle" to "ОЖИДАНИЕ",
                    "bulb.voice.listening" to "СЛУШАЕТ",
                    "bulb.voice.processing" to "ОБРАБОТКА",
                    "bulb.voice.transcribing" to "РАСПОЗНАВАНИЕ",
                    "bulb.mode.title" to "РЕЖИМ",
                    "btn.hold_to_speak" to "Удерживайте чтобы говорить",
                    "btn.recording" to "Запись... Отпустите для ввода",
                    "btn.processing" to "Обработка речи...",
                    "btn.copy" to "Копировать",
                    "btn.collapse" to "Свернуть в индикаторы",
                    "btn.expand" to "Развернуть окно",
                    "btn.hide_tray" to "Свернуть в трей",
                    "btn.exit" to "Выход из программы",
                    "btn.open_settings" to "Открыть настройки...",
                    "btn.record_shortcut" to "Записать сочетание",
                    "btn.apply" to "Применить",
                    "btn.reset_defaults" to "Сбросить по умолчанию",
                    "btn.export" to "Экспорт настроек...",
                    "btn.import" to "Импорт настроек...",
                    "btn.download_binary" to "Скачать whisper-cli",
                    "btn.browse" to "Обзор...",
                    "btn.download_model" to "Скачать модель",
                    "btn.transcribe_file" to "Распознать аудиофайл...",
                    "btn.clear_history" to "Очистить историю",
                    "label.audio_provider" to "Аудио-драйвер:",
                    "label.microphone" to "Входной микрофон / Монитор:",
                    "label.engine" to "Движок распознавания:",
                    "label.hotkey" to "Горячая клавиша PTT:",
                    "label.insertion_mode" to "Способ вставки текста:",
                    "label.timing" to "Момент вставки текста:",
                    "label.clipboard_privacy" to "Приватность буфера:",
                    "label.system_startup" to "Автозапуск:",
                    "label.whisper_exec" to "Исполняемый файл Whisper:",
                    "label.multilingual_model" to "Мультиязычная модель:",
                    "label.spoken_lang" to "Язык диктовки:",
                    "label.bilingual_mode" to "Билингвальный режим (EN + Выбранный язык)",
                    "label.inference_device" to "Устройство инференса:",
                    "label.ui_language" to "Язык интерфейса:",
                    "label.recent_speech" to "Недавняя расшифровка:",
                    "label.search_history" to "Поиск по истории:",
                    "mode.release" to "По отпусканию клавиши",
                    "mode.fly" to "На лету",
                    "mode.direct" to "Прямой ввод",
                    "mode.clipboard" to "Буфер обмена",
                    "placeholder.no_dictations" to "Диктовки отсутствуют. Удерживайте горячую клавишу или нажмите «Говорить».",
                ),
            AppLanguage.JP to
                mapOf(
                    "tab.dashboard" to "ダッシュボード",
                    "tab.settings" to "設定",
                    "tab.whisper" to "Whisperとモデル",
                    "tab.history" to "履歴",
                    "bulb.app.title" to "アプリ",
                    "bulb.app.active" to "稼働中",
                    "bulb.voice.title" to "音声",
                    "bulb.voice.idle" to "待機中",
                    "bulb.voice.listening" to "聞き取り中",
                    "bulb.voice.processing" to "処理中",
                    "bulb.voice.transcribing" to "変換中",
                    "bulb.mode.title" to "モード",
                    "btn.hold_to_speak" to "長押しで話す (PTT)",
                    "btn.recording" to "録音中... 離して確定",
                    "btn.processing" to "音声を変換中...",
                    "btn.copy" to "コピー",
                    "btn.collapse" to "ランプに折りたたむ",
                    "btn.expand" to "ウィンドウを展開",
                    "btn.hide_tray" to "トレイに格納",
                    "btn.exit" to "終了",
                    "btn.open_settings" to "設定を開く...",
                    "btn.record_shortcut" to "ショートカットを録音/登録",
                    "btn.apply" to "適用",
                    "btn.reset_defaults" to "初期設定に戻す",
                    "btn.export" to "設定を書き出し...",
                    "btn.import" to "設定を読み込み...",
                    "btn.download_binary" to "whisper-cli をダウンロード",
                    "btn.browse" to "参照...",
                    "btn.download_model" to "モデルをダウンロード",
                    "btn.transcribe_file" to "音声ファイルを変換...",
                    "btn.clear_history" to "履歴を消去",
                    "label.audio_provider" to "オーディオドライバ:",
                    "label.microphone" to "マイク / モニター:",
                    "label.engine" to "認識エンジン:",
                    "label.hotkey" to "ホットキー:",
                    "label.insertion_mode" to "テキスト挿入方式:",
                    "label.timing" to "挿入タイミング:",
                    "label.clipboard_privacy" to "クリップボード設定:",
                    "label.system_startup" to "自動起動:",
                    "label.whisper_exec" to "Whisper実行ファイル:",
                    "label.multilingual_model" to "多言語モデル:",
                    "label.spoken_lang" to "音声の言語:",
                    "label.bilingual_mode" to "バイリンガル (EN + 選択した言語)",
                    "label.inference_device" to "処理デバイス:",
                    "label.ui_language" to "UI言語:",
                    "label.recent_speech" to "最近の文字起こし:",
                    "label.search_history" to "履歴を検索:",
                    "mode.release" to "キーを離した時",
                    "mode.fly" to "リアルタイム",
                    "mode.direct" to "直接入力",
                    "mode.clipboard" to "クリップボード",
                    "placeholder.no_dictations" to "文字起こしはまだありません。ホットキーを押したまま話してください。",
                ),
            AppLanguage.CN to
                mapOf(
                    "tab.dashboard" to "仪表板",
                    "tab.settings" to "设置",
                    "tab.whisper" to "Whisper 与模型",
                    "tab.history" to "历史记录",
                    "bulb.app.title" to "程序",
                    "bulb.app.active" to "运行中",
                    "bulb.voice.title" to "语音",
                    "bulb.voice.idle" to "待命",
                    "bulb.voice.listening" to "聆听中",
                    "bulb.voice.processing" to "处理中",
                    "bulb.voice.transcribing" to "识别中",
                    "bulb.mode.title" to "模式",
                    "btn.hold_to_speak" to "按住说话 (PTT)",
                    "btn.recording" to "录音中... 松开输入",
                    "btn.processing" to "语音处理中...",
                    "btn.copy" to "复制",
                    "btn.collapse" to "折叠至指示灯",
                    "btn.expand" to "展开窗口",
                    "btn.hide_tray" to "最小化至托盘",
                    "btn.exit" to "退出程序",
                    "btn.open_settings" to "打开设置...",
                    "btn.record_shortcut" to "录制快捷键",
                    "btn.apply" to "应用",
                    "btn.reset_defaults" to "恢复默认值",
                    "btn.export" to "导出设置...",
                    "btn.import" to "导入设置...",
                    "btn.download_binary" to "下载 whisper-cli",
                    "btn.browse" to "浏览...",
                    "btn.download_model" to "下载模型",
                    "btn.transcribe_file" to "转录音频文件...",
                    "btn.clear_history" to "清空历史",
                    "label.audio_provider" to "音频驱动:",
                    "label.microphone" to "麦克风 / 监听:",
                    "label.engine" to "识别引擎:",
                    "label.hotkey" to "语音快捷键:",
                    "label.insertion_mode" to "文本插入方式:",
                    "label.timing" to "插入时机:",
                    "label.clipboard_privacy" to "剪贴板隐私:",
                    "label.system_startup" to "开机自启:",
                    "label.whisper_exec" to "Whisper 可执行文件:",
                    "label.multilingual_model" to "多语言模型:",
                    "label.spoken_lang" to "说话语言:",
                    "label.bilingual_mode" to "双语模式 (EN + 选定语言)",
                    "label.inference_device" to "计算设备:",
                    "label.ui_language" to "界面语言:",
                    "label.recent_speech" to "最近转录内容:",
                    "label.search_history" to "搜索历史:",
                    "mode.release" to "松开按键时",
                    "mode.fly" to "实时输入",
                    "mode.direct" to "直接按键模拟",
                    "mode.clipboard" to "剪贴板粘贴",
                    "placeholder.no_dictations" to "暂无听写记录。按住热键或点击开始说话。",
                ),
            AppLanguage.TR to
                mapOf(
                    "tab.dashboard" to "Kontrol Paneli",
                    "tab.settings" to "Ayarlar",
                    "tab.whisper" to "Whisper ve Modeller",
                    "tab.history" to "Geçmiş",
                    "bulb.app.title" to "UYG",
                    "bulb.app.active" to "AKTİF",
                    "bulb.voice.title" to "SES",
                    "bulb.voice.idle" to "BEKLEMEDE",
                    "bulb.voice.listening" to "DİNLİYOR",
                    "bulb.voice.processing" to "İŞLENİYOR",
                    "bulb.voice.transcribing" to "ÇEVRİLİYOR",
                    "bulb.mode.title" to "MOD",
                    "btn.hold_to_speak" to "Konuşmak İçin Basılı Tutun",
                    "btn.recording" to "Kaydediliyor... Bırakın",
                    "btn.processing" to "Ses işleniyor...",
                    "btn.copy" to "Kopyala",
                    "btn.collapse" to "Işıklara Küçült",
                    "btn.expand" to "Pencereyi Genişlet",
                    "btn.hide_tray" to "Sistem Tepsisine Küçült",
                    "btn.exit" to "Uygulamadan Çık",
                    "btn.open_settings" to "Ayarları Aç...",
                    "btn.record_shortcut" to "Kısayol Kaydet",
                    "btn.apply" to "Uygula",
                    "btn.reset_defaults" to "Varsayılana Sıfırla",
                    "btn.export" to "Ayarları Dışa Aktar...",
                    "btn.import" to "Ayarları İçe Aktar...",
                    "btn.download_binary" to "whisper-cli İndir",
                    "btn.browse" to "Gözat...",
                    "btn.download_model" to "Modeli İndir",
                    "btn.transcribe_file" to "Ses Dosyasını Çevir...",
                    "btn.clear_history" to "Geçmişi Temizle",
                    "label.audio_provider" to "Ses Sağlayıcı:",
                    "label.microphone" to "Ses Girişi / Monitör:",
                    "label.engine" to "Tanıma Motoru:",
                    "label.hotkey" to "Bas-Konuş Kısayolu:",
                    "label.insertion_mode" to "Metin Ekleme Modu:",
                    "label.timing" to "Ekleme Zamanı:",
                    "label.clipboard_privacy" to "Pano Gizliliği:",
                    "label.system_startup" to "Sistem Başlangıcı:",
                    "label.whisper_exec" to "Whisper Yürütülebilir:",
                    "label.multilingual_model" to "Çok Dilli Model:",
                    "label.spoken_lang" to "Konuşulan Dil:",
                    "label.bilingual_mode" to "İki Dilli Mod (EN + Seçilen Dil)",
                    "label.inference_device" to "İşlem Birimi:",
                    "label.ui_language" to "Arayüz Dili:",
                    "label.recent_speech" to "Son Konuşma Metni:",
                    "label.search_history" to "Geçmişte Ara:",
                    "mode.release" to "Tuş Bırakıldığında",
                    "mode.fly" to "Anlık Yazım",
                    "mode.direct" to "Doğrudan Yazma",
                    "mode.clipboard" to "Pano ile Yapıştırma",
                    "placeholder.no_dictations" to "Henüz dikte yok. Kısayol tuşunu basılı tutun veya Konuş'a basın.",
                ),
            AppLanguage.AR to
                mapOf(
                    "tab.dashboard" to "لوحة التحكم",
                    "tab.settings" to "الإعدادات",
                    "tab.whisper" to "Whisper والنماذج",
                    "tab.history" to "السجل",
                    "bulb.app.title" to "التطبيق",
                    "bulb.app.active" to "نشط",
                    "bulb.voice.title" to "الصوت",
                    "bulb.voice.idle" to "خامل",
                    "bulb.voice.listening" to "استماع",
                    "bulb.voice.processing" to "معالجة",
                    "bulb.voice.transcribing" to "تحويل",
                    "bulb.mode.title" to "الوضع",
                    "btn.hold_to_speak" to "اضغط مطولاً للتحدث",
                    "btn.recording" to "جارٍ التسجيل... اترك للإدخال",
                    "btn.processing" to "جارٍ معالجة الصوت...",
                    "btn.copy" to "نسخ",
                    "btn.collapse" to "تصغير إلى المصابيح",
                    "btn.expand" to "توسيع النافذة",
                    "btn.hide_tray" to "إخفاء في شريط المهام",
                    "btn.exit" to "إنهاء التطبيق",
                    "btn.open_settings" to "فتح الإعدادات...",
                    "btn.record_shortcut" to "تسجيل اختصار لوحة المفاتيح",
                    "btn.apply" to "تطبيق",
                    "btn.reset_defaults" to "إعادة التعيين إلى الافتراضي",
                    "btn.export" to "تصدير الإعدادات...",
                    "btn.import" to "استيراد الإعدادات...",
                    "btn.download_binary" to "تنزيل whisper-cli",
                    "btn.browse" to "استعراض...",
                    "btn.download_model" to "تنزيل النموذج",
                    "btn.transcribe_file" to "تحويل ملف صوتي...",
                    "btn.clear_history" to "مسح السجل",
                    "label.audio_provider" to "مزود الصوت:",
                    "label.microphone" to "الميكروفون / المراقبة:",
                    "label.engine" to "محرك التعرف:",
                    "label.hotkey" to "مفتاح التحدث المباشر:",
                    "label.insertion_mode" to "طريقة إدخال النص:",
                    "label.timing" to "توقيت الإدخال:",
                    "label.clipboard_privacy" to "خصوصية الحافظة:",
                    "label.system_startup" to "بدء التشغيل مع النظام:",
                    "label.whisper_exec" to "ملف تشگیر Whisper:",
                    "label.multilingual_model" to "النموذج متعدد اللغات:",
                    "label.spoken_lang" to "لغة التحدث:",
                    "label.bilingual_mode" to "الوضع ثنائي اللغة (EN + اللغة المحددة)",
                    "label.inference_device" to "جهاز المعالجة:",
                    "label.ui_language" to "لغة الواجهة:",
                    "label.recent_speech" to "آخر نص محول:",
                    "label.search_history" to "بحث في السجل:",
                    "mode.release" to "عند إفلات المفتاح",
                    "mode.fly" to "مباشر أثناء الكلام",
                    "mode.direct" to "كتابة مباشرة",
                    "mode.clipboard" to "عبر الحافظة",
                    "placeholder.no_dictations" to "لا توجد تسجيلات حتى الآن. اضغط مطولاً على مفتاح الاختصار أو اضغط على تحدث.",
                ),
            AppLanguage.ES to
                mapOf(
                    "tab.dashboard" to "Panel",
                    "tab.settings" to "Configuración",
                    "tab.whisper" to "Whisper y Modelos",
                    "tab.history" to "Historial",
                    "bulb.app.title" to "APP",
                    "bulb.app.active" to "ACTIVO",
                    "bulb.voice.title" to "VOZ",
                    "bulb.voice.idle" to "EN ESPERA",
                    "bulb.voice.listening" to "ESCUCHANDO",
                    "bulb.voice.processing" to "PROCESANDO",
                    "bulb.voice.transcribing" to "TRANSCRIBIENDO",
                    "bulb.mode.title" to "MODO",
                    "btn.hold_to_speak" to "Mantenga para hablar",
                    "btn.recording" to "Grabando... Suelte para insertar",
                    "btn.processing" to "Procesando voz...",
                    "btn.copy" to "Copiar",
                    "btn.collapse" to "Minimizar a indicadores",
                    "btn.expand" to "Expandir ventana",
                    "btn.hide_tray" to "Minimizar a la bandeja",
                    "btn.exit" to "Salir",
                    "btn.open_settings" to "Abrir configuración...",
                    "btn.record_shortcut" to "Grabar atajo",
                    "btn.apply" to "Aplicar",
                    "btn.reset_defaults" to "Restablecer valores",
                    "btn.export" to "Exportar configuración...",
                    "btn.import" to "Importar configuración...",
                    "btn.download_binary" to "Descargar whisper-cli",
                    "btn.browse" to "Examinar...",
                    "btn.download_model" to "Descargar modelo",
                    "btn.transcribe_file" to "Transcribir archivo...",
                    "btn.clear_history" to "Borrar historial",
                    "label.audio_provider" to "Proveedor de audio:",
                    "label.microphone" to "Entrada de audio / Monitor:",
                    "label.engine" to "Motor de reconocimiento:",
                    "label.hotkey" to "Atajo Push-to-Talk:",
                    "label.insertion_mode" to "Modo de inserción:",
                    "label.timing" to "Momento de inserción:",
                    "label.clipboard_privacy" to "Privacidad portapapeles:",
                    "label.system_startup" to "Inicio del sistema:",
                    "label.whisper_exec" to "Ejecutable Whisper:",
                    "label.multilingual_model" to "Modelo multilingüe:",
                    "label.spoken_lang" to "Idioma hablado:",
                    "label.bilingual_mode" to "Modo bilingüe (EN + Idioma seleccionado)",
                    "label.inference_device" to "Dispositivo de inferencia:",
                    "label.ui_language" to "Idioma de interfaz:",
                    "label.recent_speech" to "Transcripción reciente:",
                    "label.search_history" to "Buscar en historial:",
                    "mode.release" to "Al soltar la tecla",
                    "mode.fly" to "En tiempo real",
                    "mode.direct" to "Escritura directa",
                    "mode.clipboard" to "Portapapeles",
                    "placeholder.no_dictations" to "No hay dictados todavía. Presione Hablar o use su atajo.",
                ),
            AppLanguage.IT to
                mapOf(
                    "tab.dashboard" to "Pannello",
                    "tab.settings" to "Impostazioni",
                    "tab.whisper" to "Whisper & Modelli",
                    "tab.history" to "Cronologia",
                    "bulb.app.title" to "APP",
                    "bulb.app.active" to "ATTIVO",
                    "bulb.voice.title" to "VOCE",
                    "bulb.voice.idle" to "IN ATTESA",
                    "bulb.voice.listening" to "IN ASCOLTO",
                    "bulb.voice.processing" to "ELABORAZIONE",
                    "bulb.voice.transcribing" to "TRASCRIZIONE",
                    "bulb.mode.title" to "MODO",
                    "btn.hold_to_speak" to "Tieni premuto per parlare",
                    "btn.recording" to "Registrazione... Rilascia",
                    "btn.processing" to "Elaborazione voce...",
                    "btn.copy" to "Copia",
                    "btn.collapse" to "Riduci a spie luminose",
                    "btn.expand" to "Espandi finestra",
                    "btn.hide_tray" to "Riduci nella barra",
                    "btn.exit" to "Esci",
                    "btn.open_settings" to "Apri impostazioni...",
                    "btn.record_shortcut" to "Registra scorciatoia",
                    "btn.apply" to "Applica",
                    "btn.reset_defaults" to "Ripristina predefiniti",
                    "btn.export" to "Esporta impostazioni...",
                    "btn.import" to "Importa impostazioni...",
                    "btn.download_binary" to "Scarica whisper-cli",
                    "btn.browse" to "Sfoglia...",
                    "btn.download_model" to "Scarica modello",
                    "btn.transcribe_file" to "Trascrivi file audio...",
                    "btn.clear_history" to "Cancella cronologia",
                    "label.audio_provider" to "Provider audio:",
                    "label.microphone" to "Microfono / Monitor:",
                    "label.engine" to "Motore di riconoscimento:",
                    "label.hotkey" to "Scorciatoia Push-to-Talk:",
                    "label.insertion_mode" to "Modalità inserimento:",
                    "label.timing" to "Tempistica inserimento:",
                    "label.clipboard_privacy" to "Privacy appunti:",
                    "label.system_startup" to "Avvio di sistema:",
                    "label.whisper_exec" to "Eseguibile Whisper:",
                    "label.multilingual_model" to "Modello multilingue:",
                    "label.spoken_lang" to "Lingua parlata:",
                    "label.bilingual_mode" to "Modalità bilingue (EN + Lingua selezionata)",
                    "label.inference_device" to "Dispositivo di calcolo:",
                    "label.ui_language" to "Lingua interfaccia:",
                    "label.recent_speech" to "Trascrizione recente:",
                    "label.search_history" to "Cerca nella cronologia:",
                    "mode.release" to "Al rilascio tasto",
                    "mode.fly" to "In tempo reale",
                    "mode.direct" to "Digitazione diretta",
                    "mode.clipboard" to "Appunti",
                    "placeholder.no_dictations" to "Nessuna dettatura. Tieni premuto il tasto di scelta rapida o premi Parla.",
                ),
        )

    fun tr(key: String): String {
        return translations[currentLanguage]?.get(key)
            ?: translations[AppLanguage.EN]?.get(key)
            ?: key
    }
}
